import type { Metadata } from "next";
import "./globals.css";
import { quicksand } from "./UI/fonts";
import SuspenseNavbar from "./UI/suspenseNavBar";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${quicksand.className}`}>
        <SuspenseNavbar></SuspenseNavbar>
        {children}
      </body>
    </html>
  );
}
